# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
jobs:
  - job: 'unitTests'
    pool:
       vmImage: 'ubuntu-18.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7.x'
      - script: |
          pip install --user pipenv autopep8 isort pylint pytest mypy
          pipenv lock --clear
          pipenv install
          ./ci.sh
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8.x'
      - script: |
          pip install --user pipenv autopep8 isort pylint pytest mypy
          pipenv lock --clear
          pipenv install
          ./ci.sh
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9.x'
      - script: |
          pip install --user pipenv autopep8 isort pylint pytest mypy
          pipenv lock --clear
          pipenv install
          ./ci.sh

# Runs tests nightly to make sure they works against appium@beta
schedules:
  - cron: "0 0 * * *"
    displayName: Daily Nightly build (UTC)
    branches:
      include:
        - master
    always: true
